# Site settings
title: audiostronomy.org
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    making astronomy audible
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://audiostronomy.org" # the base hostname & protocol for your site
github_username:  audiostronomy

# Build settings
markdown: kramdown
keep_files: [humans.txt, robots.txt]

defaults:
    -
      scope:
        path: ""
        type: "posts"
      values:
        author: George Privon
